### PR TITLE
Take up the full device width

### PR DESCRIPTION
**Pull request by sonicx180**
I didn't have the time to test this, but does this work?

### CODE REVIEW

**Comment by VulcanWM** [comment]
someone fixed it already before lmao

**Comment by sonicx180** [comment]
oh , lmao, was doing it for bounty

**Comment by sonicx180** [comment]
How'd it get fixed?

**Comment by VulcanWM** [comment]
#53 fixed it

**Comment by sonicx180** [comment]
ok, thx. Wait, what about the navbar, is that fine?

**Comment by sonicx180** [comment]
Also, could you close the bounty then?

**Comment by VulcanWM** [comment]
> ok, thx. Wait, what about the navbar, is that fine?

nope, need to fix it

**Comment by VulcanWM** [comment]
> Also, could you close the bounty then?

waiting for the person who fixed it to apply

**Comment by sonicx180** [comment]
Oh, it was for them lol.

**Pull request closed without merging**
